[package]
name = "wms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
usb-gadget = "0.6.0"
usbd-hid = "0.7.0"
inotify = "0.10"
rusb = "0.9"
